In [67]:
import pandas as pd

In [68]:
df = pd.read_csv('amazon_sales.csv')

/tmp/ipykernel_2772/3752415901.py:1: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('amazon_sales.csv')


In [69]:
first_five_record = df.head()
first_five_record

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
0,0,405-8078784-5731545,04-30-22,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,...,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,NaN,False,Easy Ship,NaN
1,1,171-9198151-1101146,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,...,INR,406.00,BENGALURU,KARNATAKA,560085.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN
2,2,404-0687676-7273146,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,...,INR,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,True,NaN,NaN
3,3,403-9615377-8133951,04-30-22,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,...,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,NaN,False,Easy Ship,NaN
4,4,407-1069790-7240320,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,...,INR,574.00,CHENNAI,TAMIL NADU,600073.0,IN,NaN,False,NaN,NaN


In [70]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128975 entries, 0 to 128974
Data columns (total 24 columns):
 #   Column              Non-Null Count   Dtype  
---  ------              --------------   -----  
 0   index               128975 non-null  int64  
 1   Order ID            128975 non-null  object 
 2   Date                128975 non-null  object 
 3   Status              128975 non-null  object 
 4   Fulfilment          128975 non-null  object 
 5   Sales Channel       128975 non-null  object 
 6   ship-service-level  128975 non-null  object 
 7   Style               128975 non-null  object 
 8   SKU                 128975 non-null  object 
 9   Category            128975 non-null  object 
 10  Size                128975 non-null  object 
 11  ASIN                128975 non-null  object 
 12  Courier Status      122103 non-null  object 
 13  Qty                 128975 non-null  int64  
 14  currency            121180 non-null  object 
 15  Amount              121180 non-nul

In [71]:
df.describe()

,index,Qty,Amount,ship-postal-code
count,128975.000000,128975.000000,121180.000000,128942.000000
mean,64487.000000,0.904431,648.561465,463966.236509
std,37232.019822,0.313354,281.211687,191476.764941
min,0.000000,0.000000,0.000000,110001.000000
25%,32243.500000,1.000000,449.000000,382421.000000
50%,64487.000000,1.000000,605.000000,500033.000000
75%,96730.500000,1.000000,788.000000,600024.000000
max,128974.000000,15.000000,5584.000000,989898.000000


In [72]:
df.isnull().sum()

,0
index,0
Order ID,0
Date,0
Status,0
Fulfilment,0
Sales Channel,0
ship-service-level,0
Style,0
SKU,0
Category,0


In [73]:
df.sample(10)

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
95485,95485,407-5929693-8386711,06-25-22,Shipped,Amazon,Amazon.in,Expedited,JNE3730,JNE3730-KR-L,kurta,...,INR,301.0,MUMBAI,MAHARASHTRA,400087.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False
13702,13702,171-9839768-7874718,04-22-22,Cancelled,Amazon,Amazon.in,Expedited,SET345,SET345-KR-NP-XL,Set,...,NaN,NaN,"Goregaon west, MUMBAI",MAHARASHTRA,400062.0,IN,NaN,False,NaN,NaN
86342,86342,407-9232200-8137921,05-03-22,Cancelled,Amazon,Amazon.in,Expedited,J0351,J0351-SET-L,Set,...,NaN,NaN,VIZIANAGARAM,ANDHRA PRADESH,535002.0,IN,NaN,False,NaN,False
117333,117333,404-2068664-0310737,06-08-22,Shipped,Amazon,Amazon.in,Expedited,JNE3797,JNE3797-KR-XS,Western Dress,...,INR,735.0,KOZHIKODE,KERALA,673004.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False
119377,119377,402-3536288-4501149,06-07-22,Shipped,Amazon,Amazon.in,Expedited,SET389,SET389-KR-NP-XS,Set,...,INR,648.0,LUCKNOW,UTTAR PRADESH,226011.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False
78718,78718,171-3698750-1713142,05-08-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-L,kurta,...,INR,416.0,Mumbai,MAHARASHTRA,400053.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,False
25659,25659,408-1213101-9919540,04-15-22,Shipped,Amazon,Amazon.in,Expedited,JNE3405,JNE3405-KR-XS,kurta,...,INR,399.0,UDALA,ODISHA,757041.0,IN,NaN,False,NaN,NaN
51758,51758,402-0238707-1029952,05-29-22,Shipped,Amazon,Amazon.in,Expedited,SET347,SET347-KR-NP-S,Set,...,INR,852.0,MUZAFFARPUR,BIHAR,842001.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False
29066,29066,408-4479445-5850739,04-13-22,Shipped,Amazon,Amazon.in,Expedited,SET328,SET328-KR-NP-XS,Set,...,INR,635.0,NEW DELHI,DELHI,110049.0,IN,NaN,False,NaN,NaN
53813,53813,406-0082078-3981904,05-28-22,Shipped,Amazon,Amazon.in,Expedited,J0124,J0124-TP-S,Top,...,INR,570.0,MUMBAI,MAHARASHTRA,400066.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False


In [74]:
df.shape

(128975, 24)

In [75]:
df.columns.tolist()

['index',
 'Order ID',
 'Date',
 'Status',
 'Fulfilment',
 'Sales Channel ',
 'ship-service-level',
 'Style',
 'SKU',
 'Category',
 'Size',
 'ASIN',
 'Courier Status',
 'Qty',
 'currency',
 'Amount',
 'ship-city',
 'ship-state',
 'ship-postal-code',
 'ship-country',
 'promotion-ids',
 'B2B',
 'fulfilled-by',
 'Unnamed: 22']

In [76]:
df[['Amount', 'Qty']].describe()
print(df[df['Amount'] < 0].shape)

(0, 24)


In [77]:
df[df['amount'] == 0]

KeyError: 'amount'

In [ ]:
df[df['Amount'] < 0]

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
0,0,405-8078784-5731545,04-30-22,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,...,INR,-647.62,MUMBAI,MAHARASHTRA,400081.0,IN,NaN,False,Easy Ship,NaN
1,1,171-9198151-1101146,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,...,INR,-406.00,BENGALURU,KARNATAKA,560085.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN
2,2,404-0687676-7273146,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,...,INR,-329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,True,NaN,NaN
3,3,403-9615377-8133951,04-30-22,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,...,INR,-753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,NaN,False,Easy Ship,NaN
4,4,407-1069790-7240320,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,...,INR,-574.00,CHENNAI,TAMIL NADU,600073.0,IN,NaN,False,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128970,128970,406-6001380-7673107,05-31-22,Shipped,Amazon,Amazon.in,Expedited,JNE3697,JNE3697-KR-XL,kurta,...,INR,-517.00,HYDERABAD,TELANGANA,500013.0,IN,NaN,False,NaN,False
128971,128971,402-9551604-7544318,05-31-22,Shipped,Amazon,Amazon.in,Expedited,SET401,SET401-KR-NP-M,Set,...,INR,-999.00,GURUGRAM,HARYANA,122004.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False
128972,128972,407-9547469-3152358,05-31-22,Shipped,Amazon,Amazon.in,Expedited,J0157,J0157-DR-XXL,Western Dress,...,INR,-690.00,HYDERABAD,TELANGANA,500049.0,IN,NaN,False,NaN,False
128973,128973,402-6184140-0545956,05-31-22,Shipped,Amazon,Amazon.in,Expedited,J0012,J0012-SKD-XS,Set,...,INR,-1199.00,Halol,Gujarat,389350.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False


In [ ]:
df['Courier Status'].unique()

array([nan, 'Shipped', 'Cancelled', 'Unshipped'], dtype=object)

In [ ]:
df['Category'].value_counts()

,count
Category,
Set,50284
kurta,49877
Western Dress,15500
Top,10622
Ethnic Dress,1159
Blouse,926
Bottom,440
Saree,164
Dupatta,3


In [ ]:
df['Status'].unique()

array(['Cancelled', 'Shipped - Delivered to Buyer', 'Shipped',
       'Shipped - Returned to Seller', 'Shipped - Rejected by Buyer',
       'Shipped - Lost in Transit', 'Shipped - Out for Delivery',
       'Shipped - Returning to Seller', 'Shipped - Picked Up', 'Pending',
       'Pending - Waiting for Pick Up', 'Shipped - Damaged', 'Shipping'],
      dtype=object)

In [ ]:
df['currency'].unique()

array(['INR', nan], dtype=object)

In [ ]:
df['fulfilled-by'].unique()

array(['Easy Ship', nan], dtype=object)

In [ ]:
df['Fulfilment'].unique()

array(['Merchant', 'Amazon'], dtype=object)

In [ ]:
df['Sales Channel '].unique()

array(['Amazon.in', 'Non-Amazon'], dtype=object)

In [ ]:
df['ship-service-level'].unique()

array(['Standard', 'Expedited'], dtype=object)

In [ ]:
df['Size'].unique()

array(['S', '3XL', 'XL', 'L', 'XXL', 'XS', '6XL', 'M', '4XL', '5XL',
       'Free'], dtype=object)

In [ ]:
df['Qty'].unique()

array([ 0,  1,  2, 15,  3,  9, 13,  5,  4,  8])

In [ ]:
df['ship-city'].unique()

array(['MUMBAI', 'BENGALURU', 'NAVI MUMBAI', ...,
       'GULABPURA, Distt BHILWARA', 'Prayagraj (ALLAHABAD)', 'Halol'],
      dtype=object)

In [ ]:
df['ship-state'].unique()

array(['MAHARASHTRA', 'KARNATAKA', 'PUDUCHERRY', 'TAMIL NADU',
       'UTTAR PRADESH', 'CHANDIGARH', 'TELANGANA', 'ANDHRA PRADESH',
       'RAJASTHAN', 'DELHI', 'HARYANA', 'ASSAM', 'JHARKHAND',
       'CHHATTISGARH', 'ODISHA', 'KERALA', 'MADHYA PRADESH',
       'WEST BENGAL', 'NAGALAND', 'Gujarat', 'UTTARAKHAND', 'BIHAR',
       'JAMMU & KASHMIR', 'PUNJAB', 'HIMACHAL PRADESH',
       'ARUNACHAL PRADESH', 'MANIPUR', 'Goa', 'MEGHALAYA', 'GOA',
       'TRIPURA', 'LADAKH', 'DADRA AND NAGAR', 'SIKKIM', 'Delhi', nan,
       'ANDAMAN & NICOBAR ', 'Punjab', 'Rajshthan', 'Manipur',
       'rajasthan', 'Odisha', 'NL', 'Bihar', 'MIZORAM', 'punjab',
       'New Delhi', 'Rajasthan', 'Punjab/Mohali/Zirakpur', 'Puducherry',
       'delhi', 'RJ', 'Chandigarh', 'orissa', 'LAKSHADWEEP', 'goa', 'PB',
       'APO', 'Arunachal Pradesh', 'AR', 'Pondicherry', 'Sikkim',
       'Arunachal pradesh', 'Nagaland', 'bihar', 'Mizoram', 'rajsthan',
       'Orissa', 'Rajsthan', 'Meghalaya'], dtype=object)

In [ ]:
df['ship-postal-code'].unique()

array([400081., 560085., 410210., ..., 609603., 851205., 629152.])

In [ ]:
df['ship-country'].unique()

array(['IN', nan], dtype=object)

In [ ]:
(df.isnull().sum() / len(df) * 100).round(2)

,0
index,0.00
Order ID,0.00
Date,0.00
Status,0.00
Fulfilment,0.00
Sales Channel,0.00
ship-service-level,0.00
Style,0.00
SKU,0.00
Category,0.00


In [ ]:
df.duplicated().sum()

np.int64(0)